Update comchap

diff --git a/config/comskip/comchap b/config/comskip/comchap
--- a/config/comskip/comchap
+++ b/config/comskip/comchap
@@ -32,65 +32,65 @@ verbose=false
 lockfile=""
 workdir=""
 
-while [[ $# -gt 0 ]]
-do
-key="$1"
-case $key in
-    --keep-edl)
-    deleteedl=false
-    shift
-    ;;
-    --keep-meta)
-    deletemeta=false
-    shift
-    ;;
-    --verbose)
-    verbose=true
-    shift
-    ;;
-    --ffmpeg=*)
-    ffmpegPath="${key#*=}"
-    shift
-    ;;
-    --comskip=*)
-    comskipPath="${key#*=}"
-    shift
-    ;;
-    --comskip-ini=*)
-    comskipini="${key#*=}"
-    shift
-    ;;
-    --lockfile=*)
-    lockfile="${key#*=}"
-    shift
-    ;;
-    --work-dir=*)
-    workdir="${key#*=}"
-    shift
-    ;;
-    -*)
-    echo "Option $1 doesn't exist, please check the documentation"
-    exit 1
-    ;;
-    *)
-    if [ -z $infile ]; then
-      infile=$1
-      if [ ! -f "$infile" ]; then
-        echo "Inputfile '$infile' doesn't exist. Please check."
+while [[ $# -gt 0 ]]; do
+    key="$1"
+    case $key in
+        --keep-edl)
+        deleteedl=false
+        shift
+        ;;
+        --keep-meta)
+        deletemeta=false
+        shift
+        ;;
+        --verbose)
+        verbose=true
+        shift
+        ;;
+        --ffmpeg=*)
+        ffmpegPath="${key#*=}"
+        shift
+        ;;
+        --comskip=*)
+        comskipPath="${key#*=}"
+        shift
+        ;;
+        --comskip-ini=*)
+        comskipini="${key#*=}"
+        shift
+        ;;
+        --lockfile=*)
+        lockfile="${key#*=}"
+        shift
+        ;;
+        --work-dir=*)
+        workdir="${key#*=}"
+        shift
+        ;;
+        -*)
+        echo "Option $1 doesn't exist, please check the documentation"
         exit 1
-      fi
-    else
-      if [ -z $outfile ]; then
-        outfile=$1
-      else
-        echo "Error: too many parameters. Inputfile and Outputfile already defined. Please check your command."
-        exit 1
-      fi
-    fi
-    shift
-    ;;
-esac
+        ;;
+        *)
+        if [ -z "$infile" ]; then
+            infile="$1"
+            if [ ! -f "$infile" ]; then
+                echo "Inputfile '$infile' doesn't exist. Please check."
+                exit 1
+            fi
+        else
+            if [ -z "$outfile" ]; then
+                outfile="$1"
+            else
+                echo "Error: too many parameters. Inputfile and Outputfile already defined. Please check your command."
+                exit 1
+            fi
+        fi
+        shift
+        ;;
+    esac
 done
+
 
 # Setup for verbose
 exec 3>&1
